name: Sync all branches and tags

on:
  push:
    branches: ["**"]
    tags: ["**"]

concurrency:
  group: ${{ github.workflow }} # 定义并发组，基于工作流名
  cancel-in-progress: true # 启用自动取消正在进行的运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Check if TOKEN is set
      run: |
        if [[ -z "${{ secrets.TOKEN }}" ]]; then
          echo "Error: secrets.TOKEN is not set. Exiting."
          exit 1
        fi

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # 获取所有分支和标签

    - name: Push Repository
      env:
        GIT_PROVIDER: gitlab.com
        OWNER: viocha
      run: |
        REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2) # 提取当前仓库名称
        git remote add gitlab https://oauth2:${{secrets.TOKEN}}@${GIT_PROVIDER}/${OWNER}/${REPO}.git
        git push -f --all gitlab || { echo "Failed to push branches"; exit 1; }
        git push -f --tags gitlab || { echo "Failed to push tags"; exit 1; }
